version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: '00:00'
      timezone: UTC
    open-pull-requests-limit: 15
    commit-message:
      prefix: build
      include: scope
    registries:
      - npm-registry-registry-npmjs-org
    ignore:
      - dependency-name: semantic-release
        versions:
          - '>= 20.0.0'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '00:00'
      timezone: UTC
    open-pull-requests-limit: 15
    commit-message:
      prefix: build
      include: scope
