version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  lint:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - run: npm run lint
      - run: npm run size
  unit:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - run: npm run build
      - run: npm run test -- --coverage
  release:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install
      - run:
          name: Setup NPM
          command: |-
            echo $'@contentful:registry=https://registry.npmjs.org/
            //registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> ~/.npmrc
      - run:
          name: Install
          command: npm install
      - run:
          name: Release
          command: npm run semantic-release
workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - unit
      - release:
          context: dev-workflows-release
          requires:
            - unit
          filters:
            branches:
              only:
                - main
                - next
                - next-major
